### ISSUE TITLE
command infinite loop

### ISSUE THREAD

**Issue by joey-lucky** [Kononnable/typeorm-model-generator#162]
when run 
`
typeorm-model-generator -h localhost -p 3306 -d bill -u root -x 123456 -e mysql -o ./app/database/entity/ ---noConfig --case-entity pascal --case-file pascal --case-property camel

`
command infinite loop。
i have test in two computer

**Comment by Kononnable** [comment]
What do you mean by infinite loop? How does it manifest itself?

**Comment by joey-lucky** [comment]
when you run withour administrator，cmd like this
[http://www.hjoey.com/file/temp/cmd-infinite-loop.png](url)
when you run with administrator,cmd forced termination

**Comment by Kononnable** [comment]
You've run it multiple time or does it show like that on just single execution. I can't think of anything which would produce output like that.
Please check if you've got installed latest version globally - some older version didn't report every error. You may also check if same thing happens if you don't specify `-o` parameter - maybe it's something related to escaping path value.

**Comment by joey-lucky** [comment]
I have try to restart computer and test in two computer multiple time。Maybe npm install failed and lost some node modules,because chinese internet is not open to foreign.
now I have found a way to work success. First, it must be in administrator mode for open command. Second, it must be in C disk, I run success in a test directory.
thanks!!!
