### ISSUE TITLE
Map oracle Date types to timestamp

### ISSUE THREAD

**Issue by stenoid** [Kononnable/typeorm-model-generator#165]
Hello,

Is it possible to map the datatype in the generated columnvalue to a different type? In my case importing Oracle tables, I want the "Date" type fields to be rendered as a timestamp, because I want to retain the time aspects of the fields and not have it converted to a string (in TypeORM). So currently, I get something like:

```
  @Column('date', {
    name: 'BIRTH_D'
  })
  public birth_d: Date;
```

but would prefer to get:

```
  @Column('timestamp', {
    name: 'BIRTH_D'
  })
  public birth_d: Date;
```
Thanks.

**Comment by Kononnable** [comment]
Column db type will be generated as it is set in db - otherwise generated model wouldn't really suit the db. Not sure about your use case, but if you want to change column types you can just use text editor option - find and replace `@Column('date', {` replace to `@Column('timestamp', {`
However I think specifying other sql type in entity definition than it is set in db might even lead to bugs, so you should be really careful about that.

**Comment by stenoid** [comment]
It's a very specific use case admittedly - we're dealing with a very (very) large legacy database that has inconsistent usage with its date columns and to compound the situation the system also runs on MSS databases which have the same columns defined as datetimes - hence my issue with getting consistent values with TypeORM. The number of files and values that are generated make a simple replace impractical and is something we would need to automate (especially since it's still an active development database). 

The ideal option for us would be for TypeORM to handle dates and datetimes in the same way (i.e. both converted to Date objects rather than one a string and the other a date). So from what I can see our options are to have specific transformations to convert date strings to date objects behind the scenes, possibly by having a "transformer" setting in the entity definitions (which is kind of daft since it will unconvert a value that has just been converted from a date to a string by TypeORM), modify the TypeORM code for ourselves to not do the conversion above - or change all the Oracle date values to timestamps!

**Comment by Kononnable** [comment]
You don't have to replace in files one by one; most tools allow to do it for every file in a folder at once and some of them can be automated.
As for handling dates and datetimes differently - that's probably because they've got different precision. There is a proposal to use transformers instead of standard hydration process, but it isn't implemented yet.
To sum up: I can't think right now of any other way that you didn't list here. The best option really depends on your use case - unifying database columns would be probably the cleaner solution, but yet it might be the most time consuming one.
