### ISSUE TITLE
SyntaxError: Identifier expected when generating models from a PostgreSQL instance

### ISSUE THREAD

**Issue by rmolinamir** [Kononnable/typeorm-model-generator#261]
Encountered error:

```
typeorm-model-generator@0.4.1
[11:23:57 PM] Starting creation of model classes.
(node:9316) UnhandledPromiseRejectionWarning: SyntaxError: Declaration expected. (26:3)
  24 | @OneToOne(()=>Player,player=>player.users,{ onDelete:"CASCADE" })
  25 | @JoinColumn([{ name: "id", referencedColumnName: "id" },
> 26 | ])
     |   ^
  27 | 
  28 | :Player;
  29 | 
    at t (C:\node_modules\prettier\parser-typescript.js:1:285)
    at Object.parse (C:\node_modules\prettier\parser-typescript.js:14:180461)
    at Object.parse (C:\node_modules\prettier\index.js:9739:19)
    at coreFormat (C:\node_modules\prettier\index.js:13252:23)
    at format (C:\node_modules\prettier\index.js:13510:73)
    at formatWithCursor (C:\node_modules\prettier\index.js:13526:12)
    at C:\node_modules\prettier\index.js:44207:15
    at Object.format (C:\node_modules\prettier\index.js:44226:12)
    at C:\dist\src\ModelGeneration.js:60:36    
    at Array.forEach (<anonymous>)
```

Possible cause:

I believe the syntax error is caused by the new line 26?

Question:

Is it possible to disable TypeScript validation? I could manually fix these issues in the meantime.

**Comment by Kononnable** [comment]
It is possible to skip typescript validation(fresh change introduced in #259), but it isn't available in any released version yet. You can use version from github(`npm install Kononnable/typeorm-model-generator#master`) or modify those lines manually: install package as a dependency, and replace in `ModelGeneration.js` file:
```typescript
const formatted = Prettier.format(withImportStatements, {
            parser: "typescript"
        });
```
to 
```typescript
const formatted = withImportStatements;
```

Anyhow, there is an error because of line 28 - there is no field name there, it's just saying it should be of  `Player` type. However without DDL statements for the table I have no clue why there was no field name given.

**Comment by rmolinamir** [comment]
@Kononnable thank you so much for the reply, sorry it took me more than a week to reply.

This happened in a pet project in which I'm using DBeaver to architect the database since I think it's faster than doing it programmatically, at least when starting from scratch. So very likely it's something to do with that.

I ended up restructuring the DB and it did not reproduce and in the process, I lost the DDLs. However, if I run into this again I'll install the GitHub package as you said and post a DDL sample ere. Thanks so much.
