### ISSUE TITLE
Install package

### ISSUE THREAD

**Issue by anhvan-nguyen** [Kononnable/typeorm-model-generator#282]
Hi,
I can't install it, please help me.
Thank you,

<img width="1413" alt="Screen Shot 2020-06-18 at 9 55 22 PM" src="https://user-images.githubusercontent.com/7380005/85036959-f325fb80-b1ae-11ea-82ad-9bedb28eaf3e.png">

**Comment by Kononnable** [comment]
Sorry for the delay I didn't have much time for OSS lately.
This isn't directly related with `typeorm-model-generator`. Looks like one of it dependencies fails to build because lack of file permissions. It might be related to using `sudo` with `npm`. It often leads to many file privileges errors. I would encourage you to change your node installation that it won't require `sudo` to install global packages.
As for other workarounds I would suggest giving full permissions to blocked path to current user or trying to use `npx`/installing package locally instead of installing it globally.
