### ISSUE TITLE
Should be warning not error

### ISSUE THREAD

**Issue by faiwiz** [Kononnable/typeorm-model-generator#316]
Following should be warning not error on non primary key table.
Table **TABLE_NAME** has no PK.
Error occurred in typeorm-model-generator.
typeorm-model-generator@0.4.3  node@v12.6.0

Thanks.

**Comment by Kononnable** [comment]
Tables without PK are unusable by typeorm. That's why I consider trying to transform models of such tables to be an error, not a warning.
You can use `--skip-tables` or just ignore that error - as I recall it doesn't disrupt model generation - typescript definitions will be generated even if some of them might be not usable(because of no PK).
