### ISSUE TITLE
Support ormconfig.json 

### ISSUE THREAD

**Issue by Fyr** [Kononnable/typeorm-model-generator#332]
As TypeORM automatically respects ormconfig.json, why don't typeorm-model-generator supports it also?
It could be a very useful to get credentials and any other options from ormconfig.json from the same folder

**Comment by Kononnable** [comment]
`ormconfig.json` is typeorm config file. It contains options related to typeorm. They're different from`typeorm-model-generator` options because both tools have different purpose. Because of that you would have to configure `typeorm-model-generator` using two different ways(or at least two different files). For most of the use cases just db credentials are not enough.

Btw. there is much more then just ormconfig.json. As I recall there are a few file formats supported, and there are also environmental variables. All of them would have to be supported, with the same order as in typeorm etc. It could get messy very fast.

**Comment by Fyr** [comment]
Sounds non-logical. TypeORM tool does not respect TypeORM config. Why???
I need to generate a model from a table in PostgreSQL. I should run:
`typeorm-model-generator -h localhost -e postgres -d mydb -u postgres -o src/database/entity -x mypass`

My config contains all credentials for DB else I could not use it in for ex. NestJS
Lets go through your supported options:
--host - present in ormconfig (host)
--database - present (database)
--user - present (user)
--pass - present (password)
--port - present (port)
--engine - present (type)
As you can see, all required options to generate model are present in ormconfig. So why don't use it? Extra option to specify output is also in config:
"cli": {
    "entitiesDir": "src/database/entity"
If any option is ommited it should be specified manually. As most of your supported options are present in ormconfig.json I do not see any reason to not use it

**Comment by Kononnable** [comment]
>As most of your supported options are present in ormconfig.json I do not see any reason to not use it

While it's true for database credentials and similar parameters there is much more options on how to customize generated entities.
https://github.com/Kononnable/typeorm-model-generator/blob/master/src/IConnectionOptions.ts - mostly covered by typeorm options
https://github.com/Kononnable/typeorm-model-generator/blob/master/src/IGenerationOptions.ts - only one option covered
