### ISSUE TITLE
argv.s.split() is not a function => problem with argument parser

### ISSUE THREAD

**Issue by Twiggeh** [Kononnable/typeorm-model-generator#334]
In index on line 260 s / schema argument is an array, but is expected to be a string. Not sure why it is that though, it did work correctly for me when I was using it as localhost, but it broke when I pasted a url.
![image](https://user-images.githubusercontent.com/23149166/119315299-fe629080-bc75-11eb-9a09-fadde0010559.png)

Basically every input field breaks when there is an ip? I have now hardcoded the password and output url, and it works nicely :D
Seems like an upstream issue with yargs maybe ?

Node version: 16.0.0
yarn version : 1.22.10

**Comment by Kononnable** [comment]
What do you mean by url? There is no support for passing db urls(#140).

SchemaNames is an array because of possibility of passing multiple schemas(and the way of [not] putting schema names in generated code). Is it possible that some of the characters you enter are special characters for your shell, and typeorm-model-generator actually receives different input then you're writing in your shell?
