### ISSUE TITLE
{onUpdate: "NO ACTION"} does not exist in TypeOrm

### ISSUE THREAD

**Issue by miltonhowe** [Kononnable/typeorm-model-generator#71]
The generator produces `onUpdate: "NO ACTION"` which is not a valid value in TypeOrm (it does exist on OnDeleteType)

from the source code:
`export declare type OnUpdateType = "RESTRICT" | "CASCADE" | "SET NULL" | "DEFAULT";`

**Comment by scvgoe** [comment]
Is there any progress on this?

**Comment by Kononnable** [comment]
Sorry, I didn't have enough time for this project for some time. As I recall I started to fix it but encountered different behavior in typeorm depending on database driver and postponed this because of lack of time. I should have some more free time next week, so I hope I will fix some bugs :)
Current solution is to use code editor to replace all `onUpdate: "NO ACTION"` on already generated models.

**Comment by Kononnable** [comment]
Fixed in `typeorm-model-generator@0.2.20`
